# Generated by Django 4.0.3 on 2022-04-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_form', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type_form', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(max_length=10)),
                ('material_description', models.CharField(max_length=300)),
                ('order_quantity', models.IntegerField(default=0)),
                ('quantity_issued', models.IntegerField(default=0)),
                ('date_added', models.DateField()),
                ('date_issued', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.location')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.materialtype')),
            ],
        ),
    ]
