# Generated by Django 4.0.3 on 2022-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
    ]
