# Generated by Django 4.0.3 on 2022-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_inventory_date_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='date_issued',
        ),
    ]
