# Generated by Django 4.0.3 on 2022-04-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_inventory_date_added_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialType',
            new_name='Material',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_type_form',
            new_name='material_form',
        ),
    ]
