# Generated by Django 4.0.3 on 2022-04-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_form', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surgery', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('patient_code', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_contact', models.CharField(max_length=15)),
                ('medical_allergies', models.TextField()),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.bloodgroup')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.gender')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.surgery')),
            ],
        ),
    ]
