# Generated by Django 4.0.3 on 2022-04-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_bloodgroup_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgery',
            old_name='Surgery',
            new_name='surgery',
        ),
    ]
