# Generated by Django 4.0.3 on 2022-04-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_surgery_surgery_surgery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloodgroup',
            new_name='Blood_group',
        ),
        migrations.RenameField(
            model_name='blood_group',
            old_name='blood_group',
            new_name='blood_grp',
        ),
    ]
