# Generated by Django 4.0.3 on 2022-04-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_bloodgroup_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blood_group',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='blood_grp',
            new_name='group_form',
        ),
        migrations.RenameField(
            model_name='surgery',
            old_name='surgery',
            new_name='surgery_form',
        ),
    ]
