# Generated by Django 4.0.3 on 2022-03-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payroll',
        ),
    ]
